name: SonarQube

on:
  push:
    branches:
      - main
      - feature/refactor-to-microservices
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install SonarQube Cloud scanner
        shell: powershell
        run: |
          if (!(Test-Path "${{ runner.temp }}\scanner")) {
            New-Item -Path "${{ runner.temp }}\scanner" -ItemType Directory
          }
          dotnet tool update dotnet-sonarscanner --tool-path "${{ runner.temp }}\scanner"

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          Write-Host "--- START SONARSCANNER ---"
          $scannerPath = "${{ runner.temp }}\scanner\dotnet-sonarscanner.exe"
          
          & $scannerPath begin /k:"patseshankaevgeniy_InnoClinic" /o:"patseshankaevgeniy" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.skipJreProvisioning=true

          Write-Host "--- SEARCHING FOR SOLUTIONS (.sln or .slnx) ---"
          $projects = Get-ChildItem -Include *.sln, *.slnx -Recurse
          
          if ($null -eq $projects -or $projects.Count -eq 0) {
              Write-Error "CRITICAL ERROR: No .sln or .slnx files found!"
              exit 1
          }

          foreach ($sln in $projects) {
              Write-Host "BUILDING: $($sln.FullName)"
              # Сборка проекта
              dotnet build "$($sln.FullName)" --configuration Release
          }

          Write-Host "--- END SONARSCANNER ---"
          & $scannerPath end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"